### ISSUE TITLE
OutOfRange Exception upon join

### ISSUE THREAD

**Issue by bippity** [bippity/CharacterReset#2]
[12/17/16 17:19:29] [Server API] Warning: Plugin "CharacterReset" has had an unhandled exception thrown by one of its NetGetData handlers: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.NetMessage.SendDataDirect(Int32 msgType, Int32 remoteClient, Int32 ignoreClient, String text, Int32 number, Single number2, Single number3, Single number4, Int32 number5, Int32 number6, Int32 number7)
   at Terraria.NetMessage.SendData(Int32 msgType, Int32 remoteClient, Int32 ignoreClient, String text, Int32 number, Single number2, Single number3, Single number4, Int32 number5, Int32 number6, Int32 number7)
   at CharacterReset.CharacterReset.ClearInventory(TSPlayer player)
   at CharacterReset.CharacterReset.CleanInventory(Int32 who)
   at CharacterReset.CharacterReset.OnGetData(GetDataEventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

**Comment by bippity** [comment]
Inventory Index 140 is causing problems apparently

**Comment by bippity** [comment]
Problem starts here: https://github.com/bippity/CharacterReset/blob/GM/CharacterReset.cs#L164

**Comment by bippity** [comment]
#3 Fixes this
